In [17]:
import pandas as pd
# File paths
train_file = r"C:\Users\BHARGAVI\Downloads\project_data\ghc_train.csv"
test_file = r"C:\Users\BHARGAVI\Downloads\project_data\ghc_test.csv"

# Load CSV files into pandas DataFrames
df = pd.read_csv(train_file)

In [18]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming df is your DataFrame containing 'text' and 'label' columns

# Step 1: Drop rows with NaN in 'text' column
df = df.dropna(subset=['text'])

# Step 2: Split the data into X (features) and y (labels)
X = df['text']
y = df['label']

# Step 3: Initialize TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=1000)  # Adjust max_features as needed

# Step 4: Fit and transform X (text data) using TfidfVectorizer
X = tfidf_vectorizer.fit_transform(X)


In [19]:
# Step 5: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 6: Initialize and train the RandomForestClassifier model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Step 7: Make predictions
y_pred = model.predict(X_test)

# Step 8: Evaluate the model
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))


Accuracy: 0.8789896670493685
Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.99      0.93      3800
           1       0.65      0.11      0.19       555

    accuracy                           0.88      4355
   macro avg       0.77      0.55      0.56      4355
weighted avg       0.85      0.88      0.84      4355

Confusion Matrix:
 [[3766   34]
 [ 493   62]]


In [20]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB  # Naive Bayes classifier for multinomial models
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming df is your DataFrame containing 'text' and 'label' columns

# Step 1: Drop rows with NaN in 'text' column
df = df.dropna(subset=['text'])

# Step 2: Split the data into X (features) and y (labels)
X = df['text']
y = df['label']

# Step 3: Initialize TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=1000)  # Adjust max_features as needed


In [21]:
# Step 4: Fit and transform X (text data) using TfidfVectorizer
X = tfidf_vectorizer.fit_transform(X)

# Step 5: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 6: Initialize and train the Naive Bayes classifier (MultinomialNB)
model = MultinomialNB()
model.fit(X_train, y_train)

# Step 7: Make predictions
y_pred = model.predict(X_test)

# Step 8: Evaluate the model
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))

Accuracy: 0.8780711825487945
Classification Report:
               precision    recall  f1-score   support

           0       0.88      1.00      0.93      3800
           1       0.96      0.05      0.09       555

    accuracy                           0.88      4355
   macro avg       0.92      0.52      0.51      4355
weighted avg       0.89      0.88      0.83      4355

Confusion Matrix:
 [[3799    1]
 [ 530   25]]


In [22]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming df is your DataFrame containing 'text' and 'label' columns

# Step 1: Drop rows with NaN in 'text' column
df = df.dropna(subset=['text'])

# Step 2: Split the data into X (features) and y (labels)
X = df['text']
y = df['label']

# Step 3: Initialize TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=1000)  # Adjust max_features as needed

# Step 4: Fit and transform X (text data) using TfidfVectorizer
X = tfidf_vectorizer.fit_transform(X)

# Step 5: Convert TF-IDF matrix to dense format for Gaussian Naive Bayes
X = X.toarray()

# Step 6: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 7: Initialize and train the Gaussian Naive Bayes classifier
model = GaussianNB()
model.fit(X_train, y_train)

# Step 8: Make predictions
y_pred = model.predict(X_test)

# Step 9: Evaluate the model
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))


Accuracy: 0.5531572904707233
Classification Report:
               precision    recall  f1-score   support

           0       0.93      0.53      0.67      3800
           1       0.19      0.74      0.30       555

    accuracy                           0.55      4355
   macro avg       0.56      0.63      0.48      4355
weighted avg       0.84      0.55      0.62      4355

Confusion Matrix:
 [[1999 1801]
 [ 145  410]]


In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Assuming df is your DataFrame containing 'text' and 'label' columns

# Step 1: Drop rows with NaN in 'text' column
df = df.dropna(subset=['text'])

# Step 2: Split the data into X (features) and y (labels)
X = df['text']
y = df['label']

# Step 3: Initialize TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=1000)  # Adjust max_features as needed

# Step 4: Fit and transform X (text data) using TfidfVectorizer
X = tfidf_vectorizer.fit_transform(X)

# Step 5: Convert TF-IDF matrix to dense format for KNN
X = X.toarray()

In [24]:
# Step 6: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 7: Initialize and train the KNN classifier
# Adjust the number of neighbors (n_neighbors) as needed
k = 5  # Example: k=5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

# Step 8: Make predictions
y_pred = knn.predict(X_test)

# Step 9: Evaluate the model
print('Accuracy:', accuracy_score(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))


Accuracy: 0.8723306544202066
Classification Report:
               precision    recall  f1-score   support

           0       0.87      1.00      0.93      3800
           1       0.48      0.02      0.04       555

    accuracy                           0.87      4355
   macro avg       0.68      0.51      0.49      4355
weighted avg       0.82      0.87      0.82      4355

Confusion Matrix:
 [[3787   13]
 [ 543   12]]
